---
# NOTE: would ideally use the build in 'gatekeeper-manager-role' but it only gets deployed after the 'Gatekeeper' resource is deployed, so chicken/egg problem there
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gatekeeper-admin
rules:
- verbs:
  - "*"
  apiGroups:
  - operator.gatekeeper.sh
  resources:
  - '*'
  